# Generated by Django 2.2 on 2019-05-14 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Postęp', 'verbose_name_plural': 'Postępy'},
        ),
        migrations.RemoveField(
            model_name='progress',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='barcode',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='kod kreskowy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('pieces', 'surowe płytki'), ('chain', 'łańcuch'), ('welded construction', 'konstrukcja spawana')], default=0, max_length=32, verbose_name='typ zamówienia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='weld',
            field=models.NullBooleanField(verbose_name='spawanie'),
        ),
        migrations.AlterField(
            model_name='order',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='dodano przez'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='data utworzenia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='realisation_limit_date',
            field=models.DateField(verbose_name='termin realizacji'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='assembly',
            field=models.NullBooleanField(verbose_name='montaż'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='finish_status',
            field=models.BooleanField(default=False, verbose_name='status ukończenia'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='heat_treatment',
            field=models.NullBooleanField(verbose_name='hartowanie'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='progress', serialize=False, to='orders.Order', verbose_name='zamówienie'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='pieces_made',
            field=models.BooleanField(default=False, verbose_name='zrobienie płytek'),
        ),
    ]
