# Generated by Django 2.2 on 2019-06-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190514_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.Progress', verbose_name='Postęp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
